/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include "switch.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void delay_ms(uint32_t ms)
{
	for(uint32_t i=0; i<ms*4000; i++);
}

int main(void)
{
	uint8_t mode = 0;

	led_init(LED_GREEN);
	led_init(LED_ORANGE);
	led_init(LED_RED);
	led_init(LED_BLUE);
	switch_init(0);

	while(1)
	{
		if(switch_status(0) == 1)
		{
			delay_ms(200);


			while(switch_status(0) == 1);
			mode++;
			if(mode > 4)
				mode = 0;
		}
		led_off(LED_GREEN);
		led_off(LED_ORANGE);
		led_off(LED_RED);
		led_off(LED_BLUE);

		if(mode == 0)
		{

		}
		else if(mode == 1)
		{

			led_on(LED_GREEN);
		}
		else if(mode == 2)
		{

			led_on(LED_ORANGE);
		}
		else if(mode == 3)
		{

			led_on(LED_GREEN);
			led_on(LED_RED);
		}
		else if(mode == 4)
		{

			led_on(LED_GREEN);
			led_on(LED_ORANGE);
			led_on(LED_RED);
			led_on(LED_BLUE);
		}
	}
}
