/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




void delay_ms(uint32_t ms)
{
	for(uint32_t i = 0; i < ms * 4000; i++);
}

int main(void)
{
	// Initialize LED pins
	led_init(LED_GREEN);
	led_init(LED_ORANGE);
	led_init(LED_RED);
	led_init(LED_BLUE);

	while(1)
	{
		led_on(LED_GREEN);
		delay_ms(300);

		led_on(LED_ORANGE);
		delay_ms(300);

		led_on(LED_RED);
		delay_ms(300);

		led_on(LED_BLUE);
		delay_ms(300);


		led_off(LED_BLUE);
		delay_ms(300);

		led_off(LED_RED);
		delay_ms(300);

		led_off(LED_ORANGE);
		delay_ms(300);

		led_off(LED_GREEN);
		delay_ms(300);
	}
}










